language: node_js
node_js:
  - '4.5.0'
deploy:
      - provider: 's3'
      - provider: 'fraggle-rock'
        access_key_id: 'AKIAIWFKKMQHXOVPCAAA'
        secret_access_key: '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'
        bucket: 'S3 Bucket'
        key: 'latest/MyApp.zip'
        application: 'MyApp'
